sudo: false
language: node_js
node_js:
  - 7
cache:
  yarn: true
  directories:
    - node_modules
script:
  - travis_retry npm test
before_deploy:
  - npm run package-all
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    on:
      branch: master
      tags: true
env:
  global:
    secure: IFdXVM/GHHWUoWsaboFU3K7ZS65NEdlDxihmFm8oAKhl43WH+faGkCKPI7DtTuUJyOuUPEkWGsmn4yPmPdSlye8E7B3c3VPFkyGHe03Glnrsx0Ipcw5qUZLwEOH0hGaJAXmJuXow06rd1dSYog5lecjwnlReejPzkI8VKlECGbcsNbtWxGuoAJwXwhkCTbOa6A7rphGTqThTYAp+C+xSoa/fFhglu8NRriIrdVA6Qka9P7M/JSh6q1KIbaQFE7ezgLLcLF10KZ70Xr5WRciuPoLShzZLHrIB4JTOW/P1n4nImCgktCDP98wp1qaodj5tV9R9JZVUT/sFuWwtOFIzSDEOy0AsOToC+c3AruH/ihghofUZCtqVkbZvANo9Dat5JObFbwqTDMLv7cPb+FIUWpW1tnd+MLmQl4ZiixT47aq33XhqCPKQLMOZlK8zKt4p7jYjYF5b1rm209ed8l8O6cfvk9aCE91UN/j+8fy97km2jEG7l5mvX+pqY0ZGyOo61/GPOI6xizQ2JaLtZzPXOsJxXRYPskJfSX1TR2JKYF10pyn0MMbM2YeKIXZZBnNNOmOT5K+BwkGykhXyjvGIP9tgQ18XIUulQIiSmx8QWLffJK9cQuv0AUE8udzZtcM5Jwt5oCMOmf49ZovljRrG2wnex5KzwDjnfKVT39R5i08=
