sudo: false
language: node_js
node_js:
- 7
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then yarn upgrade && git diff --exit-code;
  fi
- npm run package-all
script:
- travis_retry npm test
deploy:
- provider: script
  script: npm run release
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - EXTENSION_ID=bcnkgcoohaaaclieohdlkphgfinkgbfm
  - secure: WMMEr2jhFsS8e/LFcJp5CfZEWuV4hDPHS844PzfZSmr6OL/k1C/zoUH2TQC8fB1imj9wtQd4uKekuOmn6pIXAqKGYHUcKfqqEh+DxuhvjC/IHtLXANlsHReDHDuPE9CkdtRPOQgU3D97NmFZzgb1whDDA1zZxVS8wTON9b/7IWcXXh9L2WU/m5pJzafI6PVkBWzWqOpnmOrYulP26PvtBgcc2HoqDMM3C4Jk9jkbJADhlBUHCrhCb3zDC6YJNYRps0XHkH2k1lkVjz8hiv4pL6fk8zIMUIaKL6MmYXGaNwaEDHvDD6wRqpCgUdqSUFqwoe3UlxehpWP3UtJN8Chd/79c357GboiQ6X/c21sKLhYHaHKlp5nd1MuoRdW3p9GaOfQvnaR2p1Te+6+n9qEn4wzpmmd4shsf034T0Do4KVbotknzDvj1xHkxSmEQD0gBwEjc5t7H8hpVgJ7K9E1qjP0PgVd9U07ZRxHC8q5641dEUJPqtHLD2Uky2hzx4Ox7ZdiN/CYEZzwdHaI4efBiyqCQulvtmxHn+t/TBn4Ki9MmCfT9NgJ0fcfSooFmYxNmA6X/MyzwLMNIaHwCbZsM1ZGJeB2Bcv3RM/VJIMuE0yRGuQcnPhFAcz9r+msEnjEn/qXcy9efDNzQAB8ywna/FZGcjRTn4w2r9hAxl9HRm30=
  - secure: Yse5gX5KErF8VwthtF2LgWqli4Xg6tZbxjSzXRLrbsjZ9gfS0QeXN+OeojYEEXrvYd1z2I1nFYCxcY1gmVuMMSB5L2g66En0zOy9AcR81UOC5OoiTnAT0DuuLVulROM9U2FO/vBrPDgw1ZKdTXLOtRlLJa2XMxtsMHA03q0WcubeEj45XsZBnAcT1Jhy6uqknlHCAZR6tF709d9XJuNBu8X9tBYCbXKq4YISQeTb9SwftDcZLt8/jwyHwPSFPKl5xHt4AkFGgXHMcF/7EuDo3u1crN9g7xl1XTMTROdumQXy/OFkYwYohfmiai5cyPo9UXg6Pw8yeed6TVinH3IElAPkib+H642MKM9S6kKBVAq0WDg5n+XGl+8/mf9oO3ozwy5s+hkIaru5TuwdBu1PAIso9KIPb7b258j6RXQ7BstsvBVOTQQxqGCop+DCn5ANAFJqQtdjcn07GJlVUoW5/8IzwoLXuntzjnsMGVLncsv6C2ropDHyXEH+tdz4+sNVa2PHbmmEuEDttYzgxv2CYvnZffxzvXt3ckKcqrm0HYvA3KbsrPJ0/aYU449CzBT5tYDZ92F/lckgs8DJhXe7sxuM9YuTBM/YNqOUqr9sRldg5j2/M4Ty8ropoUbqnu+7c/LywiVUIBIcj5xYrGphgofNO9UQsTDWy/fFoLRY14I=
  - secure: LaVnrsGk9PeHL2Tls4SMKqFErJEtOEUoxQimCoSSUpHI/q9+GG9pjKzfQIJ25ejFuhCcJumH0c0fi8eYgFIZ3p4k5boIr1v5A9SH9G0nDEIdTwqZZMcwtMTQhEAn64V3YDZwcgcIL9UbNd0bCwiyV/1A8IfRYWWtFQGkC6S5cxWqUge+FtGoyr6PzXA0xGG6WhoKyuXvQw/He9R8hdgXouURpP+LA1/JYVNVMMEDrB3AViMdvpLJHoNCmQJJ2rH8wsbtlEpco2P5Yqh2kKb6Fd84sLao3rGgy6tlBL6tzUEIQvK2NBxsa6vdgadvWOqfDrqx1SW/R8oXXtRR2zmU0xD+msBjqw2gAHo9UAdNzlyn70ykaSxOIjjWoF6akHzWHaE0Gbql5QC7c6lJ4wM54hPLCjTHtN3mFUD++gZ6t0UZnhhEQdfnhcsVOqeYkzh4tK0VCJv2VWaTAJ1RpVq/5XKw9TbLTD/37WBoOo/4oqODubAvZdGPFEGMwFwyRjIljEmcI7l1PaeIWZJN3pIFi+ea1XR2sAeMHe5/9zbrtPrfikSbOhoCi8hMq/OdJTIwBwm3/wPyhxhIVcU8JZaJqBZY1E3sIFk+FIg0UZoLtKrKp5qMDBAriDf+mMCg0+//LTinSrRf7e/l+U/JOWHpjSw+uEkrmhU0S4e8bvnhBqg=
  - secure: srEiojxHc60jwdShTSLWHl6K0eXSBDdWInBUHdXGOvf/crZsJu+Kgpb0HmOCfU0LUKjyI63UrRbLzDAU/RBUJCj4VHNkb0srKazUimanF52MWBD0AP+d1MgPSVy68bwpex0V4ED0OVf/7DRBj2m4ePsalgWQ/RzbgAuCO8cfKdeda3Y+S2Xbj9pkbKCqEq3WNiDZrPTJY6QsNepdtfHAjAYXyYshpw73F9TTIXkLXb9NUfD3PP1VngS5WTq3flEHbj4KvroPjTbS58B6qe0Yqc8HRcZI6c+Q0QtbuMfApNid4ge1SegobduldFto2HFofttYZ+v/SnW+wLKIrhohm0omyYV+H/pTuvzokkYrvqkTZec+7c5bK32yFQf5y0KDnmAsYws64i7g7mMH0ECwY6ckzepbKWXZg8NusIYUlbebCClj31Tkeze+cXWM12eRHoOYaqA3REoQyFs8x06F2K0c4UH5ermGatTgTXnnYFkxtYxfzeYZzsFdhDRPcetuE7xZuNYjY2lMGpxlwtDnUEn1iW8snBeB7d/gOKYgUjV+e57KznC8/niKfV6CG0INwsxAqbYyES6MmObh7V7wrUy4zYdZoRLfFOM0CMrIWWxEXvVnkYvNi8CHCCQFZCRtNe2c3dAtc8jX2VHTBUCBEjAOrOnPLxYhuzHp47zloU4=
